# 모의고사 1-2 통계분석 Q1~5

In [1]:
#---------------------------------------------------------------------------------------
# Q1) FIFA데이터에서 각 선수의 키는 Heghit변수에 피트와 인치로 입력되어 있습니다. 
#      이를 cm로 변환하여 새로운 변수 Height_cm을 생성하시오. 
#      ( “ ' ” 앞의 숫자는 피트이며, “ ' ” 뒤의 숫자는 인치, 1피트 = 30cm, 1인치 = 2.5cm)
#---------------------------------------------------------------------------------------

In [2]:
%pwd

'/home/jupyter/ADP/ADP24/2_모의고사 숙제 업로드/모의고사 1-2'

In [3]:
import pandas as pd
import numpy as np
df_fifa = pd.read_csv("FIFA.csv", encoding="cp949")
df_fifa

,ID,Name,Age,Nationality,Overall,Club,Preferred_Foot,Work_Rate,Position,Jersey_Number,Contract_Valid_Until,Height,Weight_lb,Release_Clause,Value,Wage
0,158023,L. Messi,31,Argentina,94,FC Barcelona,Left,Medium/ Medium,RF,10,2021,5'7,159,226500,110500,565
1,20801,Cristiano Ronaldo,33,Portugal,94,Juventus,Right,High/ Low,ST,7,2022,6'2,183,127100,77000,405
2,190871,Neymar Jr,26,Brazil,92,Paris Saint-Germain,Right,High/ Medium,LW,10,2022,5'9,150,228100,118500,290
3,193080,De Gea,27,Spain,91,Manchester United,Right,Medium/ Medium,GK,1,2020,6'4,168,138600,72000,260
4,192985,K. De Bruyne,27,Belgium,91,Manchester City,Right,High/ High,RCM,7,2023,5'11,154,196400,102000,355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16637,238813,J. Lundstram,19,England,47,Crewe Alexandra,Right,Medium/ Medium,CM,22,2019,5'9,134,143,60,1
16638,243165,N. Christoffersson,19,Sweden,47,Trelleborgs FF,Right,Medium/ Medium,ST,21,2020,6'3,170,113,60,1
16639,241638,B. Worman,16,England,47,Cambridge United,Right,Medium/ Medium,ST,33,2021,5'8,148,165,60,1
16640,246268,D. Walker-Rice,17,England,47,Tranmere Rovers,Right,Medium/ Medium,RW,34,2019,5'10,154,143,60,1
16641,246269,G. Nugent,16,England,46,Tranmere Rovers,Right,Medium/ Medium,CM,33,2019,5'10,176,165,60,1

In [4]:
df_fifa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16642 entries, 0 to 16641
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    16642 non-null  int64
 1   Name                  16642 non-null  object
 2   Age                   16642 non-null  int64
 3   Nationality           16642 non-null  object
 4   Overall               16642 non-null  int64
 5   Club                  16642 non-null  object
 6   Preferred_Foot        16642 non-null  object
 7   Work_Rate             16642 non-null  object
 8   Position              16642 non-null  object
 9   Jersey_Number         16642 non-null  int64
 10  Contract_Valid_Until  16642 non-null  int64
 11  Height                16642 non-null  object
 12  Weight_lb             16642 non-null  int64
 13  Release_Clause        16642 non-null  int64
 14  Value                 16642 non-null  int64
 15  Wage                  16642 non-null  int64
dtypes: int64(9), object(7)
memory usage: 2.0+ MB

In [5]:
df_fifa["Height_cm"] = df_fifa["Height"]

In [6]:
df_fifa["Height_cm"].map(lambda x: df_fifa.Height_cm.str.split("'")[0])

KeyboardInterrupt: