## 4.2 T-test

### 4.2.1 일표본 T-검정 (One-Sample T-Test)

__가.__ 일표본 T-검정 개념   
* 단일모집단에서 관심이 있는 연속형 변수의 평균값을 특정 기준값과 비교
* 가정: 모집단의 구성요소들이 정규분포를 이룬다는 가정
        * 종속변수는 연속형이어야함
        * 검증하고자 하는 기준값이 있어야함
        
        
__나.__ 일표본 T-검정 단계

|1단계: |가설설정|  |
|------|---|---|
|모수|모평균(μ)|  |
|귀무가설(H0)|μ=μ0|  |
|대립가설(H1)|(1) 양측검정: |μ!=μ0|
| |(2) 우단측검정: |μ>μ0|
| |(3) 좌단측검정: |μ<μ0|
      
      
|2단계: |유의수준 설정|          |
|------|---|---|
      
      
|3단계: |검정통계량의 값 및 유의확률 계산|  |
|------|---|---|
      
      
|4단계: |귀무가설의 기각여부 판단 및 의사결정|
|------|---|
|p-value:|유의확률|
|α: | 유의수준|
|p-value < α:|귀무가설을 기각하고, 대립가설을 채택|
|p-value > α:|귀무가설을 기각하지 않음|

![python image2](./일표본검정.png)

__[예제]__  
cats 데이터에서 고양이들의 평균몸무게가 2.6kg인지 아닌지통계적 검정을 수행하고, 결과 해석하기   
(양측검정, 유의수준 = 0.05)

In [2]:
import pandas as pd
cats=pd.read_csv('./data/cats.csv')
cats

    Sex  Bwt   Hwt
0     F  2.0   7.0
1     F  2.0   7.4
2     F  2.0   9.5
3     F  2.1   7.2
4     F  2.1   7.3
..   ..  ...   ...
139   M  3.7  11.0
140   M  3.8  14.8
141   M  3.8  16.8
142   M  3.9  14.4
143   M  3.9  20.5

[144 rows x 3 columns]