# 21회 기출문제 풀이 (2) 

## 머신 러닝 (50점)
학생 성적에 관한 데이터세트 제공 394행짜리 소규모 데이터.


1.4. 데이터 분할 방법을 2가지 쓰고 적절한 데이터 분할을 적용. 선택한 이유 설명.<br>
1.5. svm, xgboost, randomforest 3개의 알고리즘 공통점을 쓰고 이 예측 분석에 적합한 알고리즘인지 설명.<br>
1.6. 세 가지 모델 모두 모델링 해보고 가장 적합한 알고리즘 선택하고 이유 설명. 한계점 설명하고 보완 가능한 부분 설명. <br>
현업에서 사용시 주의할 점 등에 대해 기술.<br>

In [1]:
import pandas as pd
import numpy as np 
df = pd.read_csv("./student_data_2.csv")
df

,school,sex,paid,activities,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,grade
0,1,0,0,0,4.0,3.0,4.0,1.0,1,3.0,6.0,5,6,6
1,1,0,0,0,5.0,3.0,3.0,1.0,1,3.0,4.0,5,5,6
2,1,0,1,0,4.0,3.0,2.0,2.0,3,3.0,10.0,7,8,10
3,1,0,1,1,3.0,2.0,2.0,1.0,1,5.0,2.0,15,14,15
4,1,0,1,0,4.0,3.0,2.0,1.0,2,5.0,4.0,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,0,1,1,0,5.0,5.0,4.0,4.0,5,4.0,11.0,9,9,9
391,0,1,0,0,2.0,4.0,5.0,3.0,4,2.0,3.0,14,16,16
392,0,1,0,0,5.0,5.0,3.0,3.0,3,3.0,3.0,10,8,7
393,0,1,0,0,4.0,4.0,1.0,3.0,4,5.0,0.0,11,12,10
394,0,1,0,0,3.0,2.0,3.0,3.0,3,5.0,5.0,8,9,9

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    int64
 1   sex         395 non-null    int64
 2   paid        395 non-null    int64
 3   activities  395 non-null    int64
 4   famrel      395 non-null    float64
 5   freetime    395 non-null    float64
 6   goout       395 non-null    float64
 7   Dalc        395 non-null    float64
 8   Walc        395 non-null    int64
 9   health      395 non-null    float64
 10  absences    395 non-null    float64
 11  G1          395 non-null    int64
 12  G2          395 non-null    int64
 13  grade       395 non-null    int64
dtypes: float64(6), int64(8)
memory usage: 43.3 KB

## 1.4. 데이터 분할 방법을 2가지 쓰고 적절한 데이터 분할을 적용. 선택한 이유 설명.

1) 랜덤 분할 
 - train test데이터셋을 나누어서 학습된 데이터를 검증할 수 있음 
 - 분할 시에 무작위로 사용자가 지정하여 비율로 분할 함 
 - 전체 분석 데이터 중 머신러닝 모델을 학습시키기 위한 학습용 데이터와 테스트 데이터를 나누어서 적용시키는 이유는 
   모델 결과가 다른 데이터에도 적용 가능한지, 일반화가 가능한지를 검증하기 위함이다. 
 
2) 층화 추출 기법 
- 종속변수의 클래스의 비율이 학습용 데이터와 테스트용 데이터에 비율이 같게 분할함 
- 클래스의 편향을 막을 수 있음 
- 종속변수가 범주형 변수인 분류분석에 사용 



해당 데이터는 종속변수가 연속형이므로, 회귀분석을 사용한다. 그러므로 층화추출기법을 사용한 분할이 아닌 랜덤 샘플링을 통한 분할을 사용하여, 7:3 비율로 분할하였다.

In [3]:
X = df.drop('grade',axis=1)
y = df['grade']

from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=2022)

## 1.5. svm, xgboost, randomforest 3개의 알고리즘 공통점을 쓰고 이 예측 분석에 적합한 알고리즘인지 설명.

* 회귀분석과 분류분석을 모두 할 수 있는 분석알고리즘이다. 
* 모두 범주형 변수를 독립변수로 사용할 수 없어 변환을 해주어야 한다. 
* 과대 적합 과소적합을 막기위한 매개변수의 설정이 필요하다.

* 해당 데이터에서는 종속변수의 값이 연속형이므로 회귀분석이 적합하다.

## 1.6. 세 가지 모델 모두 모델링 해보고 가장 적합한 알고리즘 선택하고 이유 설명. 한계점 설명하고 보완 가능한 부분 설명.
현업에서 사용시 주의할 점 등에 대해 기술.

In [4]:
from sklearn.svm import SVR 
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns)
X_test_scaled = pd.DataFrame(scaler.transform(X_test), columns=X_test.columns)

In [7]:
from sklearn.model_selection import GridSearchCV

param_grid = [
    { 'C': [0.1, 1,10,100],'gamma': [0.001, 0.01, 0.1, 1, 10]}
]

grid_svm = GridSearchCV(SVR(), param_grid =param_grid, cv = 5)
grid_svm.fit(X_train_scaled, y_train)

result = pd.DataFrame(grid_svm.cv_results_['params'])
result['mean_test_score'] = grid_svm.cv_results_['mean_test_score']
result.sort_values(by='mean_test_score', ascending=False)

        C   gamma  mean_test_score
15  100.0   0.001         0.815206
11   10.0   0.010         0.813794
16  100.0   0.010         0.800047
10   10.0   0.001         0.740380
12   10.0   0.100         0.719862
6     1.0   0.010         0.703161
17  100.0   0.100         0.675613
7     1.0   0.100         0.609533
5     1.0   0.001         0.203629
2     0.1   0.100         0.186046
1     0.1   0.010         0.157252
18  100.0   1.000         0.063825
13   10.0   1.000         0.062787
8     1.0   1.000        -0.002093
0     0.1   0.001        -0.005152
3     0.1   1.000        -0.025950
9     1.0  10.000        -0.026642
19  100.0  10.000        -0.027140
14   10.0  10.000        -0.028213
4     0.1  10.000        -0.028769

In [9]:
svr = SVR(C=100, gamma = 0.001) 
svr.fit(X_train_scaled, y_train)
print("R2 : ", svr.score(X_test_scaled, y_test))
print("RMSE:", np.sqrt(mean_squared_error(y_test,svr.predict(X_test_scaled))))

R2 :  0.790510351393822
RMSE: 2.143350008868285

In [10]:
rf = RandomForestRegressor(n_estimators=1000) 
rf.fit(X_train, y_train)
rf.score(X_test, y_test)
print("R2 : ", rf.score(X_test, y_test))
print("RMSE:", np.sqrt(mean_squared_error(y_test,rf.predict(X_test))))

R2 :  0.8615096359277388
RMSE: 1.7426958277046398

In [11]:
xgb = XGBRegressor(n_estimators =1000, max_depth=11) 
xgb.fit(X_train, y_train)
xgb.score(X_test, y_test)
print("R2 : ", xgb.score(X_test, y_test))
print("RMSE:", np.sqrt(mean_squared_error(y_test,xgb.predict(X_test))))

R2 :  0.8780574257556419
RMSE: 1.6352700864014305